In [1]:
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
import numpy as np
from mpl_toolkits.mplot3d import Axes3D


In [2]:
def pca(data, label, color):
    pca = PCA(n_components=3)
    pca.fit(data)
    data = pca.transform(params)
    ax.plot(data[:, 0], data[:, 1], data[:, 2], label=label, color=color)


In [28]:
def merge(format_str, iterations):
    return [np.load(format_str.format(i))['arr_0'] for i in range(0, iterations, 100)]

In [29]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')


In [ ]:
pca(merge('../results/densenet_0.0/param_hist_{}.npz', 10000), 'Densenet Baseline', 'black')
pca(merge('../results/densenet_100.0k/param_hist_{}.npz', 10000), 'Densenet 100K', 'blue')
pca(merge('../results/densenet_500.0k/param_hist_{}.npz', 10000), 'Densenet 600K', 'red')

[array([-0.25166664, -0.19576064,  0.131355  , ...,  0.00257004,
        -0.00490632,  0.00236389], dtype=float32),
 array([-0.2232756 , -0.17985581,  0.1477663 , ...,  0.00665419,
        -0.04175222,  0.0121734 ], dtype=float32),
 array([-0.17662118, -0.13637215,  0.18096505, ...,  0.02401404,
        -0.04684279,  0.03592451], dtype=float32),
 array([-0.15116139, -0.1184269 ,  0.19926712, ..., -0.00723644,
        -0.05354599,  0.01075289], dtype=float32),
 array([-0.12484823, -0.10299892,  0.20963357, ..., -0.01209436,
        -0.05521253,  0.03810471], dtype=float32),
 array([-0.0936585 , -0.08730014,  0.2148609 , ...,  0.00167631,
        -0.04999923,  0.02282883], dtype=float32),
 array([-0.07216986, -0.07741095,  0.2281222 , ...,  0.00338132,
        -0.0631512 ,  0.02054755], dtype=float32),
 array([ 0.00589777, -0.01912267,  0.27945855, ..., -0.00525874,
        -0.09208572,  0.00864868], dtype=float32),
 array([-0.02298769, -0.04776566,  0.251451  , ..., -0.0393635 ,
       